baseurl = "http://localhost:1313/"
title = "blog page"
canonifyurls = true
languagecode = "en"
theme = "black-and-light"
staticDir = ["static"]

pygmentsstyle       = "bw"
pygmentscodefences  = true

[params]
  sitename = "Nived's Archive"
  disableWebFonts = false

[[menu.main]]
    name = "Homepage"
    url  = "https://nivedwho.github.io/"

[[menu.main]]
    name = "About"
    url  = "https://nivedwho.github.io/about"

[[menu.main]]
    name = "GitHub"
    url  = "https://github.com/nivedwho"


